name: First run-name
on:
  push:
    branches:
      - main
jobs:
  simple-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello, GitHub Actions!"
      - name: Print OS Release Information
        run: cat /etc/os-release

  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Current Date and Time
        run: 'echo "Current date and time: $(date)"'
      - name: List Files in Current Directory
        run: ls -la

  third_job:
    runs-on: ubuntu-latest
    needs: simple-job
    steps:
      - name: deploy for a bit
        run: sleep 10

  forth_job:
    runs-on: ubuntu-latest
    needs: [simple-job, second-job, third_job]
    steps:
      - name: Print Disk Usage
        run: sleep 10
