name: First run-name
on:
  push:
    branches:
      - main
jobs:
  simple-job:
    runs-on: ubuntu-latest
    steps:
      - name: step 1
        run: |
          pwd
          ls -la
          hostname
      - name: checkout
        uses: actions/checkout@v5
      - name: step 3
        run: |
          echo 'pwd' >> singlefile2.txt
          mkdir artifacts
          echo 'ls -la' >> artifacts/folderlist.txt
          echo 'hostname' >> artifacts/hostname.txt
      - name: upload single file
        uses: actions/upload-artifact@v7.0.1
        with:
          name: singlefile
          path: ./singlefile.txt
      - name: upload folder
        uses: actions/upload-artifact@v7.0.1
        with:
          name: my-artifact
          path: /artifact/singlefile2.txt
